# https://docs.travis-ci.com/user/build-config-imports/
version: ~> 1.0

# Import shared travis config
import:

  # `deep_merge_append` does seem to do anything, and `mode` in general, appear not to work correctly
  # current behaviour is that everything acts as if the default is `deep_merge_prepend`, so the order that
  # includes are listed does matter
  # in particular, `behat` needs to be included before `main`, though in the state of `mode` this means
  # we actually need to include it afterwards

  # main
  - source: creative-commoners/silverstripe-framework:travis-shared/main.yml@pulls/4/shared-travis-config
    mode: deep_merge_append

  # behat
  - source: creative-commoners/silverstripe-framework:travis-shared/behat.yml@pulls/4/shared-travis-config
    mode: deep_merge_append

  # jobs-behat
  - source: creative-commoners/silverstripe-framework:travis-shared/jobs-behat.yml@pulls/4/shared-travis-config
    mode: deep_merge_append

  # jobs-npm
  - source: creative-commoners/silverstripe-framework:travis-shared/jobs-npm.yml@pulls/4/shared-travis-config
    mode: deep_merge_append

  # jobs-main
  - source: creative-commoners/silverstripe-framework:travis-shared/jobs-main.yml@pulls/4/shared-travis-config
    mode: deep_merge_append

env:
  global:
    - COMPOSER_ROOT_VERSION=1.x-dev
    - GENERAL_RECIPE_EARLIEST_MINOR_VERSION=4.x-dev
    - GENERAL_RECIPE_LATEST_MINOR_VERSION=4.x-dev
    - BEHAT_SUITE=@asset-admin
    - REQUIRE_CMS_RECIPE=1
    - REQUIRE_RECIPE_TESTING=1
    - REQUIRE_FRAMEWORKTEST=1
    # - RECIPE_TESTING_VERSION=^2 # << confirmed this WILL override the shared-config value

# Confirmed this works:
# PHPCS_TEST=3 weird value to test that we can have additional matrix entries on a per module basis
jobs:
  include:
    - php: 7.4
      env:
        - DB=MYSQL
        - PHPCS_TEST=3 
        - GENERAL_RECIPE_VERSION=4.x-dev
